function para_timing_quant(output_dir)
%PARA_TIMING_QUANT Generate beamforming scan timing JSON and C source.
this_dir = fileparts(mfilename('fullpath'));
addpath(fullfile(this_dir, 'scripts'));
if nargin < 1 || isempty(output_dir)
    output_dir = fullfile(this_dir, '..', 'configs');
end

t1 = 10;
t2 = 125;
t3 = 3;
t4 = t2 + t3 + 275;
t6 = t4 + 256;
t7 = 2048;
t5 = t6 + t7 - t4;

rtc_period = t6 + t7;
rtc_dot = t7;
rtc_down = 0;

t_timing_words = uint32([rtc_dot, rtc_period, t1, t2, t3, t4, t5, t6, t7, rtc_down]);

write_bram_json( ...
    output_dir, ...
    't_timing_default.json', ...
    'Beamforming scan timing generated by para_timing_quant.m', ...
    {'t_timing'}, ...
    {t_timing_words});
write_C_array_file( ...
    fullfile(output_dir, 'c_array', 'T_timing.c'), ...
    'u32 T_timing_hex[]', t_timing_words, 4, numel(t_timing_words), ...
    '', '', true);
end
