function para_fdemod_quant(output_dir)
%PARA_FDEMOD_QUANT Generate demodulation coefficient JSON and C source.
this_dir = fileparts(mfilename('fullpath'));
addpath(fullfile(this_dir, 'scripts'));
if nargin < 1 || isempty(output_dir)
    output_dir = fullfile(this_dir, '..', 'configs');
end

fs = 25e6;
f0 = 4.0e6;
depth = 8192;

x = (0:depth-1) / fs;
w = 2 * pi * f0;

sin_coef = sin(w * x);
cos_coef = cos(w * x);

word_length = 17;
frac_length = 16;
sin_words = quantize_signed_words(sin_coef, word_length, frac_length);
cos_words = quantize_signed_words(cos_coef, word_length, frac_length);

write_bram_json( ...
    output_dir, ...
    'demod_coeffs_default.json', ...
    'Demodulation coefficients generated by para_fdemod_quant.m', ...
    {'fdemod_sin', 'fdemod_cos'}, ...
    {sin_words, cos_words});
demod_output_path = fullfile(output_dir, 'c_array', 'demod_coeffs.c');
write_C_array_file( ...
    demod_output_path, ...
    'u32 fdemod_sin_array[]', sin_words, 5, 32, sprintf('\t'), ...
    sprintf('#include "bram.h"\n\n\n'));
write_C_array_file( ...
    demod_output_path, ...
    'u32 fdemod_cos_array[]', cos_words, 5, 32, sprintf('\t'), ...
    sprintf('\n'), false, true);
end
