function para_sin_beta_quant(output_dir)
%PARA_SIN_BETA_QUANT Generate depth delay increment JSON and C source.
this_dir = fileparts(mfilename('fullpath'));
addpath(fullfile(this_dir, 'scripts'));
if nargin < 1 || isempty(output_dir)
    output_dir = fullfile(this_dir, '..', 'configs');
end

word_length = 20;
frac_length = 18;

angles_deg = linspace(-45, 45, 64);
angles_rad = angles_deg * pi / 180;
sin_vals = sin(angles_rad);

sin_words = quantize_signed_words(sin_vals, word_length, frac_length);

write_bram_json( ...
    output_dir, ...
    'sin_beta_default.json', ...
    'Depth delay increment coefficients generated by para_sin_beta_quant.m', ...
    {'sin_beta'}, ...
    {sin_words});
write_C_array_file( ...
    fullfile(output_dir, 'c_array', 'sin_beta_hex.c'), ...
    'u32 sin_beta_hex[]', sin_words, 5, 16,  sprintf('\t'));
end
