function para_log_quant(output_dir)
%PARA_LOG_QUANT Generate log transform table JSON and C source.
this_dir = fileparts(mfilename('fullpath'));
addpath(fullfile(this_dir, 'scripts'));
if nargin < 1 || isempty(output_dir)
    output_dir = fullfile(this_dir, '..', 'configs');
end

N = 1024;
x = 1:N;
log_table = log10(x);

word_length = 16;
frac_length = 14;
log_words = quantize_unsigned_words(log_table, word_length, frac_length);

write_bram_json( ...
    output_dir, ...
    'log_table_default.json', ...
    'Log transform table generated by para_log_quant.m', ...
    {'log_table'}, ...
    {log_words});
write_C_array_file( ...
    fullfile(output_dir, 'c_array', 'log_table_hex.c'), ...
    'u32 log_table_hex[]', log_words, 4, 16,  sprintf('\t'));
end
