function para_x_element_quant(output_dir)
%PARA_X_ELEMENT_QUANT Generate element coordinate JSON and C source.
this_dir = fileparts(mfilename('fullpath'));
addpath(fullfile(this_dir, 'scripts'));
if nargin < 1 || isempty(output_dir)
    output_dir = fullfile(this_dir, '..', 'configs');
end

c = 1540000;
fs = 25e6;

element_num = 64;
pitch = 0.3;

x_ele = ((0:element_num-1) - (element_num-1) / 2) .* pitch;
ele_x_quant = round(x_ele / (c / fs));
ele_x_words = quantize_integer_words(ele_x_quant, 16);

write_bram_json( ...
    output_dir, ...
    'x_element_default.json', ...
    'Element coordinates generated by para_x_element_quant.m', ...
    {'x_element'}, ...
    {ele_x_words});
write_C_array_file( ...
    fullfile(output_dir, 'c_array', 'x_element_hex.c'), ...
    'u32 x_element_hex[]', ele_x_words, 4, 16,  sprintf('\t'));
end
