function para_transmit_delay(output_dir)
%PARA_TRANSMIT_DELAY Generate transmit delay profile JSON.
if nargin < 1 || isempty(output_dir)
    output_dir = default_config_dir();
end

pitch       = 0.254e-3;
element_num = 64;
c           = 1540;
F           = 80e-3;
nxmits      = 64;

idx = (0:element_num-1)';
probe_geometry_vectors = zeros(element_num, 3);
probe_geometry_vectors(:, 1) = (idx - (element_num-1) / 2) * pitch;

angles = linspace(-45, 45, nxmits);
theta = deg2rad(angles);

xx = F * sin(theta);
yy = zeros(1, nxmits);
zz = F * cos(theta);

delay = zeros(nxmits, element_num);
for i = 1:nxmits
    delay(i, :) = cal_phased_array_transmit_delay( ...
        probe_geometry_vectors, [xx(i), yy(i), zz(i)], F, c);
end

delay_int = int32(floor(delay / 10e-9));

grp1_addr = [40, 41, 42, 43, 44, 45, 46, 47];
grp1_hreg = [16, 12, 8, 4, 15, 11, 7, 3];
grp1_lreg = [14, 10, 6, 2, 13, 9, 5, 1];

grp2_addr = [32, 33, 34, 35, 36, 37, 38, 39];
grp2_hreg = [32, 28, 24, 20, 31, 27, 23, 19];
grp2_lreg = [30, 26, 22, 18, 29, 25, 21, 17];

delay_fpga = uint32([]);
all_ones = uint32(2^32 - 1);

for i = 1:nxmits
    delay_data = int32(delay_int(i, :));

    for k = 0:1
        for j = 0:15
            if j < 8
                g1_reg = grp1_addr(j+1);
                g1_hch = grp1_hreg(j+1) - 1;
                g1_lch = grp1_lreg(j+1) - 1;

                g2_reg = grp2_addr(j+1);
                g2_hch = grp2_hreg(j+1) - 1;
                g2_lch = grp2_lreg(j+1) - 1;

                chip1 = delay_data(1:32);
                delay_fpga(end+1) = uint32(g1_reg); %#ok<AGROW>
                delay_fpga(end+1) = pack_delay_pair(chip1(g1_hch+1), chip1(g1_lch+1)); %#ok<AGROW>
                delay_fpga(end+1) = uint32(g2_reg); %#ok<AGROW>
                delay_fpga(end+1) = pack_delay_pair(chip1(g2_hch+1), chip1(g2_lch+1)); %#ok<AGROW>

                chip2 = delay_data(33:64);
                delay_fpga(end+1) = uint32(g1_reg); %#ok<AGROW>
                delay_fpga(end+1) = pack_delay_pair(chip2(g1_hch+1), chip2(g1_lch+1)); %#ok<AGROW>
                delay_fpga(end+1) = uint32(g2_reg); %#ok<AGROW>
                delay_fpga(end+1) = pack_delay_pair(chip2(g2_hch+1), chip2(g2_lch+1)); %#ok<AGROW>
            elseif j == 8
                if k == 0
                    delay_fpga = append_words(delay_fpga, [uint32(26), uint32(0), uint32(26), uint32(0), ...
                                                           uint32(26), all_ones, uint32(26), all_ones]);
                else
                    delay_fpga = append_words(delay_fpga, [uint32(26), all_ones, uint32(26), all_ones, ...
                                                           uint32(26), uint32(0), uint32(26), uint32(0)]);
                end
            else
                delay_fpga = append_words(delay_fpga, zeros(1, 8, 'uint32'));
            end

            if j == 15
                delay_fpga(end) = uint32(9);
            end
        end
    end
end

write_bram_json( ...
    output_dir, ...
    'delay_profile_default.json', ...
    'Transmit delay profile generated by para_transmit_delay.m', ...
    {'delay_profile'}, ...
    {delay_fpga});
end

function word = pack_delay_pair(high_delay, low_delay)
high_word = uint32(mod(double(high_delay), 2^16));
low_word = uint32(mod(double(low_delay), 2^16));
word = bitor(bitshift(high_word, 16), low_word);
end

function words = append_words(words, values)
words = [words, uint32(values)]; %#ok<AGROW>
end

function delay_vec = cal_phased_array_transmit_delay(probe_geometry_vectors, focus_point, F, c)
fp = focus_point(:)';
diff = probe_geometry_vectors - fp;
L = sqrt(sum(diff .^ 2, 2));
% delay_vec = 5e-6 - (L - F) / c;
delay_vec = (max(L) - L) / c;
end
