function para_log_quant(output_dir)
%PARA_LOG_QUANT Generate log transform table JSON.
if nargin < 1 || isempty(output_dir)
    output_dir = default_config_dir();
end

N = 1024;
x = 1:N;
log_table = log10(x);

word_length = 16;
frac_length = 14;
log_words = quantize_unsigned_words(log_table, word_length, frac_length);

write_bram_json( ...
    output_dir, ...
    'log_table_default.json', ...
    'Log transform table generated by para_log_quant.m', ...
    {'log_table'}, ...
    {log_words});
end
