function para_dfilter_quant(output_dir)
%PARA_DFILTER_QUANT Generate dynamic filter coefficient JSON.
if nargin < 1 || isempty(output_dir)
    output_dir = default_config_dir();
end

fs = 25e6;
fc = 1.5e6;
wn = fc / (fs / 2);

N = 63;
fir_coe = fir1(N, wn, 'low');

word_length = 16;
frac_length = 11;
fir_words = quantize_signed_words(fir_coe, word_length, frac_length);

write_bram_json( ...
    output_dir, ...
    'dfilter_default.json', ...
    'Dynamic filter coefficients generated by para_dfilter_quant.m', ...
    {'dfilter'}, ...
    {fir_words});
end
